### ISSUE TITLE
JAVASCRIPT API #1

### ISSUE THREAD

**Issue by AutomataXRWrks** [AutomataXRWrks/SpaceNeoTracker#4]

**Comment by mxmar0k** [comment]
The APIs for Rover Photos and Near Earth Objects has been added to the JS.

Both apis have a thing in common to access their information, the date (YYYYMMDD).

Since it is a lot of information, and since all the dates are not linear for the rovers. We decided to grab the info for the rovers and sort the dates, we retrieve 10 random dates to access both API's information. 

The rover API fetches 5 photos (we reduced the limit, because sometimes they are a lot, and I mean a lot of pictures).

Since we are using the same date, the other api retrieves the first 5 objects near earth on that day, and appends to the page the relevant information.
